import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const projectFile = (path: string) => fileURLToPath(new URL(`../../${path}`, import.meta.url));

function sourceWindow(source: string, marker: string, length: number) {
  const index = source.indexOf(marker);
  expect(index, `Missing marker: ${marker}`).toBeGreaterThanOrEqual(0);
  return source.slice(index, index + length);
}

describe("single write page redesign contract", () => {
  it("uses the new outreach component library for the compose workflow", async () => {
    const appSource = await readFile(projectFile("apps/renderer/src/App.tsx"), "utf8");
    const composeView = sourceWindow(appSource, "{letterView === 'compose' ? (", 9000);

    expect(appSource).toContain("from './components/outreach-ui.js'");
    expect(composeView).toContain("<OutreachCard");
    expect(composeView).toContain("<OutreachField");
    expect(composeView).toContain("<OutreachInput");
    expect(composeView).toContain("<OutreachButton");
    expect(composeView).toContain("<OutreachTimeline");
    expect(composeView).toContain("<OutreachEmailEditor");
    expect(composeView).toContain("<OutreachStickyActionBar");
  });

  it("keeps generated single-write drafts on the compose page for review", async () => {
    const appSource = await readFile(projectFile("apps/renderer/src/App.tsx"), "utf8");
    const autoGenerate = sourceWindow(appSource, "async function autoGenerateDraft()", 1800);

    expect(autoGenerate).toContain("setGenerationMode('single')");
    expect(autoGenerate).toContain("setDraft(next)");
    expect(autoGenerate).toContain("setDraftSubject(next.subject)");
    expect(autoGenerate).toContain("setDraftBody(next.body)");
    expect(autoGenerate).not.toContain("setLetterView('leads')");
  });

  it("styles compose results as one clean review workspace", async () => {
    const stylesSource = await readFile(projectFile("apps/renderer/src/styles.css"), "utf8");

    expect(stylesSource).toMatch(/\.letter-single-result\s*\{[\s\S]*?display:\s*grid/);
    expect(stylesSource).toMatch(/\.letter-single-result-grid\s*\{[\s\S]*?grid-template-columns:\s*minmax\(0,\s*0\.92fr\) minmax\(280px,\s*0\.38fr\)/);
    expect(stylesSource).toMatch(/\.letter-single-review-panel\s*\{[\s\S]*?background:\s*#ffffff/);
  });
});
